documents = [
    {
        "id": "doc1",
        "topic": "Return Policy",
        "content": """Our return policy is designed to make your shopping experience worry-free. You can return most items within 30 days of the delivery date for a full refund or exchange. To be eligible for a return, items must be unused, unwashed, and in their original packaging with all tags attached. Certain items such as perishables, digital downloads, gift cards, and intimate apparel are not eligible for returns due to hygiene and safety reasons. To initiate a return, log into your account, go to 'My Orders', select the item you wish to return, and follow the prompts. You will receive a prepaid return shipping label via email within 24 hours. Once we receive and inspect the returned item, we will process your refund within 5–7 business days. If the return is due to a defective or incorrect item, we will cover all return shipping costs. For items purchased during special sales or promotions, the same 30-day return window applies unless otherwise stated. We recommend keeping your order confirmation email as proof of purchase for all returns."""
    },
    {
        "id": "doc2",
        "topic": "Refund Policy",
        "content": """We offer full refunds on eligible returned items. Once your return is received and inspected at our warehouse, you will receive an email notification confirming approval or rejection of your refund. If approved, your refund will be processed and automatically applied to your original payment method within 5–7 business days. For credit card payments, it may take an additional 3–5 business days for the refund to appear on your statement, depending on your bank. If you paid via UPI, net banking, or digital wallets, refunds are typically processed faster, within 2–3 business days. In case of a partial refund (for items returned in a non-original condition), we will notify you of the adjusted refund amount. If you haven't received your refund after 10 business days, please check with your bank before contacting us. Shipping charges are non-refundable unless the return is due to our error. We do not offer cash refunds for in-store purchases; store credit or exchange is provided instead."""
    },
    {
        "id": "doc3",
        "topic": "Shipping Time",
        "content": """We offer multiple shipping options to meet your delivery needs. Standard shipping typically takes 5–7 business days from the date of order confirmation. Express shipping is available for an additional fee and delivers within 2–3 business days. Same-day delivery is available for select pin codes in major metro cities if the order is placed before 12:00 PM local time. International shipping is available to over 50 countries and typically takes 10–15 business days, depending on the destination and customs processing. All orders are processed within 1–2 business days after payment confirmation. You will receive a shipping confirmation email with a tracking number once your order has been dispatched. Shipping times may be longer during peak seasons such as festivals, holidays, and sale events. Free standard shipping is available on all orders above ₹499. Orders containing multiple items may ship separately if items are stored in different warehouses."""
    },
    {
        "id": "doc4",
        "topic": "Order Cancellation",
        "content": """You can cancel your order at any time before it has been shipped. To cancel, go to 'My Orders' in your account dashboard and click 'Cancel Order' next to the relevant order. If the cancellation is successful, you will receive a confirmation email and a full refund will be initiated to your original payment method within 5–7 business days. If your order has already been shipped, you cannot cancel it directly — you will need to wait for delivery and then initiate a return. Orders that are in 'Processing' or 'Packing' status can still be cancelled but may require contacting our customer support team immediately. We do not charge any cancellation fees. If you placed a pre-order or a custom product order, cancellation may not be possible after 24 hours of placing the order. Repeated cancellations from the same account may result in temporary restrictions on order placement to prevent misuse of our cancellation policy."""
    },
    {
        "id": "doc5",
        "topic": "Payment Methods",
        "content": """We accept a wide range of payment methods to make your shopping experience convenient. You can pay using major credit cards including Visa, MasterCard, and American Express. Debit cards from all major Indian banks are also accepted. We support UPI payments through apps like Google Pay, PhonePe, and Paytm. Net banking is available for over 50 banks. Digital wallets such as Amazon Pay, Mobikwik, and Freecharge are also accepted. For customers who prefer not to pay upfront, we offer Cash on Delivery (COD) for eligible pin codes with a small convenience fee. Equated Monthly Installments (EMI) are available on credit cards and select debit cards for orders above ₹3,000 without any additional cost through select bank partnerships. Buy Now Pay Later (BNPL) options are available via ZestMoney and LazyPay. All transactions on our platform are secured using 256-bit SSL encryption for your safety."""
    },
    {
        "id": "doc6",
        "topic": "Product Warranty",
        "content": """Most products sold on our platform come with a manufacturer's warranty. The warranty period varies by product category: electronics typically carry a 1-year warranty, home appliances carry a 1–2 year warranty, and mobile phones carry a 1-year warranty with optional extended plans. Warranty coverage includes manufacturing defects, hardware malfunctions, and component failures under normal usage conditions. It does not cover physical damage, water damage, unauthorized modifications, or damage caused by misuse. To claim warranty, you must provide proof of purchase (order ID or invoice). You can initiate a warranty claim by contacting the manufacturer directly or through our customer support portal. Some products also offer an extended warranty option at the time of purchase for an additional fee. Third-party sellers may have different warranty policies, which will be mentioned on the product listing page. Always read the warranty card included in the product box for specific terms and conditions."""
    },
    {
        "id": "doc7",
        "topic": "Delivery Delays",
        "content": """While we strive to deliver all orders within the promised timeframe, delivery delays can sometimes occur due to unforeseen circumstances. Common reasons for delays include extreme weather conditions, natural disasters, strikes or public disruptions, high order volumes during sale seasons, incorrect or incomplete shipping address provided by the customer, and customs clearance delays for international orders. If your order is delayed, you will receive an automated notification via email and SMS with an updated estimated delivery date. You can also check the real-time status of your order by visiting 'My Orders' and clicking on the tracking link. If your order has not arrived within 10 business days of the estimated delivery date, please contact our support team with your order ID. In case of significant delays caused by us or our logistics partners, you may be eligible for a delivery fee refund or a discount coupon for your next purchase."""
    },
    {
        "id": "doc8",
        "topic": "Customer Support",
        "content": """Our customer support team is available to assist you with any queries or issues related to your orders, products, or account. You can reach us through the following channels: Live Chat is available on our website and app from 9:00 AM to 9:00 PM, Monday to Saturday. Email support is available at support@shopassist.com with a typical response time of 24–48 hours. Phone support is available at 1800-123-4567 (toll-free) from 9:00 AM to 6:00 PM on weekdays. For urgent issues such as missing orders or payment failures, please use the Live Chat option for the fastest response. When contacting support, please have your order ID, registered email address, and a brief description of the issue ready to help us resolve your concern faster. Our support team is trained to handle returns, refunds, order tracking, product complaints, and account-related issues. We aim to resolve all complaints within 72 hours of receiving them."""
    },
    {
        "id": "doc9",
        "topic": "Exchange Policy",
        "content": """We offer hassle-free exchanges on most products within 15 days of delivery. If you received the wrong size, color, or a defective product, you are eligible for a free exchange. To initiate an exchange, go to 'My Orders', select the item, and choose 'Exchange' from the options. You will be prompted to select the reason for exchange and your preferred replacement item. Our team will schedule a pickup of the original item and dispatch the replacement simultaneously in most cases. If the replacement item is of a higher value, you will need to pay the difference. If it is of lower value, the difference will be refunded to your original payment method. Exchanges are subject to stock availability. If your desired replacement is out of stock, we will offer you a full refund instead. Items must be returned in their original condition with all tags, packaging, and accessories intact to qualify for an exchange. Custom or personalized products are not eligible for exchange."""
    },
    {
        "id": "doc10",
        "topic": "Order Tracking",
        "content": """Tracking your order on ShopAssist is simple and convenient. Once your order is dispatched, you will receive a shipping confirmation email containing your tracking number and a link to the courier's tracking page. You can also track your order directly from our platform by logging into your account, navigating to 'My Orders', and clicking 'Track Order' next to your order. Real-time tracking updates are available at every stage — from order placed, to packed, dispatched, out for delivery, and delivered. We partner with leading courier services including BlueDart, Delhivery, Ekart, and Xpressbees for reliable tracking. If the tracking link is not working or the status has not been updated for more than 48 hours, please contact our customer support with your order ID. For Cash on Delivery orders, tracking begins once the order is confirmed and packed. International orders may have a gap in tracking updates during customs processing, which is normal."""
    }
]